---
title: "Launchtails - Nested Routes"
type: "challenge"
description: "View drinks within a given category and add some moderation features"
visibility: "assign"
ignore:
  - "launchtails-nested-routes.md"
